3_asp_net/lab2-GodBastardNeil-main/Lab2/Pages/Change.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab2.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Lab2.Pages
{
    public class ChangeModel : PageModel
    {
        private readonly Stud_Info_Repos Repositary;

        [BindProperty(Name = "data")]
        public Stud_Info Stud { get; set; }

        public ChangeModel(Stud_Info_Repos rep)
        {
            Repositary = rep;
            Console.WriteLine($"CreateModel");
        }

        public void OnGet(int id)
        {
            Stud_Info tmp = Repositary.Find(id);
            Console.WriteLine($"OnGet - {tmp.Id}, {tmp.FIO}, {tmp.IsStar}");
            ViewData["dStud"] = tmp;
        }

        public IActionResult OnPost()
        {
            Console.WriteLine($"OnPost - {Stud.Id}, {Stud.FIO}, {Stud.IsStar}");
            Repositary.Update(Stud);
            return RedirectToPage("Index");
        }
    }
}

3_asp_net/lab2-GodBastardNeil-main/Lab2/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

3_asp_net/lab2-GodBastardNeil-main/Lab2/Pages/Index.cshtml.cs
using Lab2.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab2.Pages
{
    public class IndexModel : PageModel
    {
        private readonly Stud_Info_Repos Repositary;

        public IndexModel(Stud_Info_Repos rep)
        {
            Repositary = rep;
        }

        public void OnGet()
        {
            ViewData["data"] = Repositary.Read_List();
        }

        public IActionResult OnPostDelete(int id)
        {
            Console.WriteLine($"del - {id}");
            Repositary.Remove(id);
            return RedirectToPage("Index");
        }
    }
}

3_asp_net/lab2-GodBastardNeil-main/Lab2/Pages/Change.cshtml
@page  "{id:int}"
@model ChangeModel
@{
    ViewData["Title"] = "Change data";
    Stud_Info dStud = (Stud_Info)ViewData["dStud"];
}

<div class="text-center">
    <h1 class="display-4">Студент</h1>

    <div class="form_data_inc_block">
        <p class="form_data_inc_block_head_text">Измените данные</p>

        <form class="form_data_inc_style" method="post">

            <snap>
                <label>Номер зачётки: </label>
                <input type="number" name="data.Id" value="@dStud.Id" readonly>
            </snap>

            <snap><input name="data.FIO" value="@dStud.FIO" required></snap>

            <snap>
                <label>Староста? </label>
                @if (dStud.IsStar)
                {
                    <input type="checkbox" name="data.IsStar" placeholder="Укажите староста ли студент" value="true" checked>
                } else
                {
                    <input type="checkbox" name="data.IsStar" placeholder="Укажите староста ли студент" value="true">
                }

            </snap>

            <snap><button class="form_inc_data" type="submit" name="form_inc_submit">Ок</button></snap>

            <snap><a class="nav-link text-dark" asp-area="" asp-page="/Index">Отмена</a></snap>

        </form>
    </div>
</div>

3_asp_net/lab2-GodBastardNeil-main/Lab2/Pages/Create.cshtml
@page
@model CreateModel
@{
    ViewData["Title"] = "Create data";
}

<div class="text-center">
    <h1 class="display-4">Студент</h1>

    <div class="form_data_inc_block">
        <p class="form_data_inc_block_head_text">Введите данные</p>
        <form class="form_data_inc_style" method="post">

            <snap><input type="number" name="data.Id" placeholder="Введите номер зачётки" required></snap>

            <snap><input name="data.FIO" placeholder="Введите ФИО" required></snap>

            <snap>
                <label for="data_inc_check">Староста? </label>
                <input type="checkbox" name="data.isStar" placeholder="Укажите староста ли студент" value="true">
            </snap>

            <snap><button class="form_inc_data" type="submit" name="form_inc_submit">Ок</button></snap>

            <snap><a class="nav-link text-dark" asp-area="" asp-page="/Index">Отмена</a></snap>

        </form>
    </div>
</div>

3_asp_net/lab2-GodBastardNeil-main/Lab2/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Data list";
    List<Stud_Info> L_students = (List<Stud_Info>)ViewData["data"];
}
@using Data

<div class="text-center">
    <table class="list_of_stud_block" width="100%" border="1">
        <caption>Список студентов</caption>
        <tr>
            <th>Номер зачётки</th>
            <th>ФИО</th>
            <th>Признак старосты</th>
            <th>Действие</th>
        </tr>

        @if (L_students != null)
        {
            Console.WriteLine("print_list");
            @foreach (Stud_Info stud in L_students)
            {
                <tr>
                    <td>@stud.Id</td>
                    <td>@stud.FIO</td>
                    <td>@stud.IsStar</td>
                    <td>
                        <form method="post">
                            <a asp-area="" asp-page="/Change" asp-route-id="@stud.Id">Изменить</a>
                            /
                            <button type="submit" asp-page-handler="delete" asp-route-id="@stud.Id">
                                Удалить
                            </button>
                        </form>
                    </td>
                </tr>
            }
        } else { Console.WriteLine("no print_list"); }
        <!--<tr>
        <td></td>
    </tr>-->
    </table>
</div>

3_asp_net/lab2-GodBastardNeil-main/Lab2/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Список студентов группы</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Create">Добавить</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Lab2 - Izmailov Neil
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>