3_asp_net/lab3/Lab3/Controllers/GroupController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3.Controllers
{
    public class GroupController : Controller
    {
        private GroupRepository GR;

        private readonly ILogger<GroupController> _logger;

        public GroupController(ILogger<GroupController> logger, GroupRepository rep)
        {
            _logger = logger;
            GR = rep;
        }

        public async Task<IActionResult> Index()
        {
            return View(await GR.List());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(GroupModel gr)
        {
            await GR.Add(gr);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            return View(await GR.GetById(Id));
        }
        [HttpPost]
        public async Task<IActionResult> Update(GroupModel gr)
        {
            await GR.Update(gr);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            await GR.Remove(Id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

3_asp_net/lab3/Lab3/Controllers/StudentController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3.Controllers
{
    public class StudentController : Controller
    {
        private StudentRepository SR;
        private GroupRepository GR;

        private readonly ILogger<StudentController> _logger;

        public StudentController(ILogger<StudentController> logger, StudentRepository rep, GroupRepository rep_of_group)
        {
            _logger = logger;
            SR = rep;
            GR = rep_of_group;
        }

        public async Task<IActionResult> Index(int Id)
        {
            ViewBag.idgroup = Id;
            ViewBag.name = (await GR.GetById(Id)).name;
            return View(await SR.List(Id));
        }

        [HttpGet]
        public async Task<IActionResult> Create(int Id)
        {
            ViewBag.idgroup = Id;
            ViewBag.name = (await GR.GetById(Id)).name;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(StudentModel st)
        {
            await SR.Add(st);
            return RedirectToAction("Index", new { Id = st.idgroup });
        }
        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            var st_to_upd = await SR.GetById(Id);
            ViewBag.name = (await GR.GetById(st_to_upd.idgroup)).name;
            return View(st_to_upd);
        }
        [HttpPost]
        public async Task<IActionResult> Update(StudentModel st)
        {
            await SR.Update(st);
            return RedirectToAction("Index", new { Id = st.idgroup });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            await SR.Remove(Id);
            return Redirect(Request.Headers["Referer"].ToString());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

3_asp_net/lab3/Lab3/Views/Group/Create.cshtml
@{
    ViewData["Title"] = "Добавление новой группы";
}

<div class="text-center">
    <h1 class="display-4">Добавление новой группы</h1>
    <form method="post" class="text-left">
        <snap>
            <label for="name"><b>Название:</b></label>
            <input type="text" name="name" id="name" class="w-100" required>
        </snap>
        <input type="submit" value="Сохранить">
    </form>
</div>

3_asp_net/lab3/Lab3/Views/Group/Index.cshtml
@model IEnumerable<Lab3.Models.GroupModel>
@{
    ViewData["Title"] = "Список групп";
}

<div class="text-center">
    <h1 class="display-4">Список групп</h1>
    <form method="post">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Название</th>
                    <th scope="col">Действие</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var gr in Model)
                {
                    <tr>
                        <td scope="row">@gr.idgroup</td>
                        <td class="w-100">@gr.name</td>
                        <td nowrap>
                            <a class="btn btn-outline-primary" asp-controller="Group" asp-action="Update"
                            asp-route-id="@gr.idgroup">Изменить</a> /
                            <input class="btn btn-danger" type="submit" value="Удалить"
                            asp-action="Delete" asp-route-id="@gr.idgroup"> /
                            <a class="btn btn-outline-success" asp-controller="Student" asp-action="Index"
                            asp-route-id="@gr.idgroup">Открыть</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
    <a class="btn btn-outline-primary" asp-controller="Group" asp-action="Create">Добавить новую группу</a>
</div>

3_asp_net/lab3/Lab3/Views/Group/Update.cshtml
@model Lab3.Models.GroupModel
@{
    ViewData["Title"] = "Редактирование группы";
}

<div class="text-center">
    <h1 class="display-4">Редактирование группы</h1>
    <form method="post" class="text-left">
        <input type="text" name="idgroup" id="idgroup" value="@Model.idgroup" hidden>
        <p>
            <label for="name"><b>Название:</b></label><br>
            <input type="text" name="name" id="name" value="@Model.name" class="w-100" required>
        </p>
        <input type="submit" value="Сохранить">
    </form>
</div>